# Generated by Django 6.0 on 2025-12-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="present",
            field=models.BooleanField(default=True),
        ),
    ]
